use_frameworks!

platform :ios, '8.0'

target 'CocoDemo_Example' do
  pod 'CocoDemo', :path => '../'

  target 'CocoDemo_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
